# 1、Numpy属性介绍

In [1]:
#导包
import numpy as np

In [2]:
import sys
print(sys.executable)

D:\anaconda3\envs\my_env_data_ana\python.exe


## 1.1、创建ndarray对象


In [3]:
#numpy是一个和数学操作相关的库，numpy的数组是多维的，并且是固定类型，数组关键字是ndarray，主要用于：矩阵运算
#创建ndarray对象，注意ndarray的下标以及从0开始
arr1 = np.arange(15).reshape(3, 5)
print(arr1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## 1.2、演示numpy的常用属性

In [4]:
print(f'numpy的轴:{arr1.ndim}')   #ndim 不是维度，是轴，也就是嵌套了几层
print(f'numpy的维度:{arr1.shape}')   #shape 维度，几行几列
print(f'numpy的元素类型:{arr1.dtype}')   #元素类型
print(f'numpy的元素个数:{arr1.size}')   #元素个数
print(f'numpy的元素占用字节数:{arr1.itemsize}')   #

numpy的轴:2
numpy的维度:(3, 5)
numpy的元素类型:int64
numpy的元素个数:15
numpy的元素占用字节数:8


## 1.3、常用的创建ndarray对象的几种方式

In [5]:
#array()函数，把python列表转换为ndarray对象
my_list = [1,2,3,4,5,6,8]
arr2 = np.array(my_list)
print(arr2)
print(type(arr2))

[1 2 3 4 5 6 8]
<class 'numpy.ndarray'>


In [6]:
#arange()函数创建ndarray对象。格式arange(起始，结束，步长，dtype=类型)，类似于range函数，返回的是ndarray对象
arr3=np.arange(0,14,2,dtype=np.int32)
print(arr3)
print(type(arr3))
print(f'元素的类型：{arr3.dtype}')

[ 0  2  4  6  8 10 12]
<class 'numpy.ndarray'>
元素的类型：int32


In [7]:
#随机数生成ndarray对象
#random.rand()生成0.0~1.0之间，包左不包右的小数矩阵
arr4=np.random.rand(3,5)    #3行5列
print(arr4)
print(type(arr4))


[[0.13644111 0.37020294 0.94602568 0.17499365 0.03103561]
 [0.7582881  0.17145336 0.53098625 0.87806822 0.4274615 ]
 [0.83833307 0.3607407  0.41109944 0.34270663 0.63528328]]
<class 'numpy.ndarray'>


In [8]:
#random.randint(起始值，结束值，size=（行，列）)生成指定范围，包左不包右的整数矩阵
arr5=np.random.randint(1,99,size=(5,5))    #3行5列
print(arr5)
print(type(arr5))

[[90 75 59 80 64]
 [18 72  3 32 62]
 [58  6 84 73 76]
 [49 59 83 91 84]
 [15 32 92 63 86]]
<class 'numpy.ndarray'>


In [9]:
#random.randuniform(起始值，结束值，size=（行，列）)生成指定范围，包左不包右的随机小数矩阵
arr6=np.random.uniform(1,99,size=(5,5))    #3行5列
print(arr6)
print(type(arr6))

[[37.23697435 56.35241787  1.19177297 21.40584706 71.61125435]
 [76.46061789 98.62808684 25.41599105 19.54690287 92.92692527]
 [48.3060728  22.65870131 30.25085564 13.73569941 84.0530905 ]
 [39.49822491 93.60445447 96.57070935 28.57220209 74.581361  ]
 [54.71915829 75.96078246 72.76214975 29.04104878 16.52791295]]
<class 'numpy.ndarray'>


## 1.4numpy类型转换 astype()

In [10]:
#创建ndarray对象
arr7=np.random.randint(1,3,size=(2,2))
print(arr7)
print(type(arr7))
print(arr7.dtype)
#把arr6转换为其他类型
arr8=arr7.astype(np.int64)
print(arr8.dtype)

[[1 2]
 [1 2]]
<class 'numpy.ndarray'>
int32
int64


## 1.5等差数列与等比数列

In [11]:
#np.logspace(a,b,n,base=k)以a为开始，b为结束，取n个等间隔点，生成k为底的等比数列.base为设置底数，默认为10
a=np.logspace(0,9,10)
print(a)
b=np.logspace(0,9,10,base=2)
print(b)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09]
[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


In [12]:
#np.linspace(a,b,n,endpoint=false)以a开始，b结束，取n个等间隔点，生成等差数列，endpoint决定了知否包含b
b=np.linspace(1,5,5,endpoint=True)  #包括尾数时，等比计算为(b-a)/(n-1)
print(b)
b=np.linspace(1,5,5,endpoint=False) #不包括尾数时，等比计算为(b-a)/n
print(b)
c=np.linspace(1,5,6,endpoint=False)
print(c)


[1. 2. 3. 4. 5.]
[1.  1.8 2.6 3.4 4.2]
[1.         1.66666667 2.33333333 3.         3.66666667 4.33333333]


## 1.6、numpy内置函数

### 常用函数

In [13]:
#1、创建标准正态分布序列,如果想改变方差和标准差，就加常数乘系数
arr1=np.random.randn(3,5)
print(arr1)

[[ 0.31300729 -0.0503075   0.08878551 -1.03209209  1.52603066]
 [ 0.88950553  0.69180517  0.55787314 -1.11216947  1.09541912]
 [-1.58345754 -0.52207753  0.35229341 -1.11456123  1.7429757 ]]


In [ ]:
#2、测试基本函数
print(np.ceil(arr1))    #向上取整，比它大的最小的那个整数
print(np.floor(arr1))   #向下取整
print(np.rint(arr1))    #四舍五入
print(np.abs(arr1))     #绝对值
print(np.multiply(arr1,arr1)) #对应元素相乘
print(arr1*arr1)               #对应元素相乘
# print(np.matmul(arr1,arr1))     #矩阵乘法
# print(arr1@arr1)                #矩阵乘法
print(np.where(arr1>0,1,-1))     #如果元素大于0就变成1，否则变成负一，类似于三元表达式

### 统计函数

In [22]:
arr2=np.arange(0,9).reshape(3,3)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [23]:
print(np.cumsum(arr2))  #累加和，前面所有元素累加到当前元素
print(np.sum(arr2,axis=0))     #所有元素求和,axis=0表示按列求和

[ 0  1  3  6 10 15 21 28 36]
[ 9 12 15]


### 去重函数

In [32]:
arr1 = np.array([[1,2,3],[3,3,5]])
print(arr1)
print(np.unique(arr1)) #去重，会返回新的数组


[[1 2 3]
 [3 3 5]]
[1 2 3 5]


### 排序函数

In [34]:
#sort函数，numpy的sort函数会返回一个新的数组，而python自带的sort是列表方法，会直接修改原列表
arr2=[1,54,2,3,4,5,19]
arr3=np.sort(arr2)
print(arr3)
arr2.sort()
print(arr2)

[ 1  2  3  4  5 19 54]
[1, 2, 3, 4, 5, 19, 54]


### 三种不同的矩阵乘法的区别

In [ ]:
"""
    假设A和B是满足矩阵乘法的两个举证
    1、dot函数：
        常见写法：C=np.dot(A,B);C=A.dot(B);
    2、matmul函数：
        常见写法：C=np.matmul(A,B)
    3、基础语法：A@B
    注意：当A和B为一维向量时，dot和matmul函数会计算向量的内积
         当A和B为二位向量时，三者没有任何区别
         当A和B为三维已上向量时，例如A的纬度（10,3，4），代表有10个3×4矩阵，B的纬度为（10，4,5）
         matmul函数会把这10个矩阵分别进行乘法操作，得到10个（3.5）的矩阵；
         @同上
         而dot函数则有一套更特殊的计算规则
"""