# Pandas数据类型

### 核心数据类型：Series和Dataframe

# 1、Series数据类型

In [ ]:
'''
Series可以理解为一行或一列数据，类似于一维数组，由索引index和值value组成
在Pandas中其实是没有行的概念的，任何数据取出来都是以列的形式
'''
import pandas as pd
import numpy as np

## 1、1创建Series对象

In [9]:
#自定义Series对象
s1=pd.Series([1,2,3,4,5])   #没有写index，就会默认自增索引
print(s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [4]:
#自定义Series对象，采用自定义索引
s2=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])   #列表形式，常用形式
s22=pd.Series([i for i in range(5)],index=['a','b','c','d','e'])    #列表推导式
print(s2)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [7]:
#自定义Series对象，采用元组形式
s3=pd.Series((1,2,3,4,5),index=('a','b','c','d','e'))   #元组形式，元组是不可变对象，传给pandas之后，会被转换成index对象
print(s3)
#自定义Series对象，采用词典形式
s4=pd.Series({'a':1,'b':2,'c':3,'d':5})   #词典形式
print(s4)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
c    3
d    5
dtype: int64


In [10]:
#采用numpy创建Series对象
s5=pd.Series(np.arange(5))
print(s5)

0    0
1    1
2    2
3    3
4    4
dtype: int64


## 1、2Series对象的属性

In [15]:
#构建Series对象
s6=pd.Series(data=[i for i in range(6)],index=[j for j in 'ABCDEF'])    #列表推导式
print(s6)

A    0
B    1
C    2
D    3
E    4
F    5
dtype: int64


In [16]:
#获取Series对象的索引列
print(s6.index)

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='str')


In [17]:
#获取Series对象的值
print(s6.values)

[0 1 2 3 4 5]


In [21]:
#根据索引获取元素
print(s6['D'])

3


In [22]:
#根据索引修改Series对象的元素值
s6['A']=39
print(s6)

A    39
B     1
C     2
D     3
E     4
F     5
dtype: int64


# 2、Dataframe数据类型

In [ ]:
#Dataframe是一个类似于二维数组或表格的对象，即有行索引（index），又有列索引（solumns）
#axis=0，代表行索引，sum(axis=0)代表，按上下的方向求和，最后得到一行，axis=1则代表按左右的方向进行操作，最后得到一列

## 2、1创建Dataframe对象

In [26]:
#采用字典+列表形式创建，在字典里面嵌套列表
info = {
    '姓名':['zbw','xjx','myy','shy'],
    '年龄':[18,18,18,18],
    '性别':['男','女','男','女'],
}
#将上述数据封装成Dataframe对象
d1=pd.DataFrame(data=info,index=['a','b','c','d'])  #默认情况下，字典的键名就是列名，值就是列数据
print(d1)

    姓名  年龄 性别
a  zbw  18  男
b  xjx  18  女
c  myy  18  男
d  shy  18  女


In [31]:
#字典套字典套列表
info={'a':{'姓名':'zbw','年龄':18,'性别':'男'},
      'b':{'姓名':'myy','年龄':18,'性别':'男'},
      'c':{'姓名':'xjx','年龄':18,'性别':'女'},        #字典套字典的情况下，外层字典的键名为列名。内层字典的键名为行名
}
d2=pd.DataFrame(data=info)
print(d2)

      a    b    c
姓名  zbw  myy  xjx
年龄   18   18   18
性别    男    男    女


In [34]:
#列表套元组、列表套列表
info=[['zbw',18,'nan'],
      ['myy',18,'nan'],
      ['xjx',18,'nv'],
]
info=[  ('zbw',18,'nan'),
        ('myy',18,'nan'),
        ('xjx',18,'nv'),
]
d3=pd.DataFrame(data=info,index=['a','c','b'],columns=['姓名','年龄','性别'])
print(d3)

    姓名  年龄   性别
a  zbw  18  nan
c  myy  18  nan
b  xjx  18   nv


In [38]:
#通过numpy的ndarray对象，创建Dataframe对象
#创建ndarray对象
a1=np.arange(0,12).reshape(3,4)
print(a1)
d4=pd.DataFrame(data=a1,index=[1,2,3],columns=['a','b','c','d'])
print(d4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
   a  b   c   d
1  0  1   2   3
2  4  5   6   7
3  8  9  10  11


## Dataframe数据类型简单案例

In [41]:
#生成10名同学5门功课的成绩，范围40-100
info=np.random.randint(40,101,(10,5))
print(info)

[[95 79 93 98 75]
 [40 56 97 60 48]
 [80 90 97 83 46]
 [81 74 53 99 68]
 [51 81 95 95 48]
 [68 49 55 63 81]
 [51 55 58 59 77]
 [63 45 98 81 46]
 [83 64 89 77 76]
 [93 98 85 43 43]]


In [ ]:
#封装为Dataframe对象
score_list=pd.DataFrame(info)
print(score_list)

In [47]:
#修改行索引与列名字
b=info.shape    #结果为元组，第一个数据为行数，也就是学生数
print(b)
index_name=['学生'+str(i+1) for i in range(info.shape[0])]
column_name=['语文','数学']

(10, 5)
